# Generated by Django 4.0.4 on 2022-04-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadesModel',
            fields=[
                ('label', models.IntegerField(primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=25, max_digits=30)),
                ('longitude', models.DecimalField(decimal_places=25, max_digits=30)),
                ('alcaldia', models.TextField()),
            ],
            options={
                'verbose_name': 'Unidad',
                'verbose_name_plural': 'Unidades',
                'db_table': 'Unidades',
                'ordering': ['label'],
            },
        ),
    ]
