# Generated by Django 4.0.4 on 2022-04-15 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadesmodel',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
